services:
  db:
    container_name: 'db'
    image: 'postgres:17.11-alpine'
    environment:
      - 'POSTGRES_DB=hbookstore_db'
      - 'POSTGRES_PASSWORD=hbookstore_password'
      - 'POSTGRES_USER=hbookstore_user'
    ports:
      - '5432:5432'