package org.example.hbookstore.author.mapping;

import org.example.hbookstore.author.api.dto.AuthorResponse;
import org.example.hbookstore.author.api.dto.CreateAuthorRequest;
import org.example.hbookstore.author.api.dto.UpdateAuthorRequest;
import org.example.hbookstore.author.domain.Author;
import org.springframework.stereotype.Component;

import java.time.Instant;

@Component
public class AuthorMapper {

    public Author toEntity(CreateAuthorRequest request) {
        return new Author(
                null, // ID will be generated by the database
                request.firstName(),
                request.lastName(),
                request.nationality(),
                Instant.now(),
                Instant.now()
        );
    }

    public Author updateEntity(Author author, UpdateAuthorRequest request) {
        if (request.firstName() != null) {
            author.setFirstName(request.firstName());
        }
        if (request.lastName() != null) {
            author.setLastName(request.lastName());
        }
        if (request.nationality() != null) {
            author.setNationality(request.nationality());
        }
        author.setUpdatedAt(Instant.now());
        return author;
    }

    public AuthorResponse toResponse(Author author) {
        return new AuthorResponse(
                author.getId(),
                author.getFirstName(),
                author.getLastName(),
                author.getNationality(),
                author.getCreatedAt(),
                author.getUpdatedAt()
        );
    }
}
